addons:
  ssh_known_hosts:
    - github.com:22
# only trigger on master branch
branches:
  only:
    - master
language: generic
# GLOBAL VARIABLES
env:
  global:
    - secure: 'PV2KkGzydmthyivpZNnOxDBzJpC4Z0kg4PPIYPJU8LhsVhNoB5etB8UzoDDIU/DrHFpyiT3Y7I4i326wTizf9FmCCY9dEXlrJoye3ZhKoCaO9eRo6Hio1KgubbqkFvALkFT0XWivKRufbbD7L6rqlLVSylD577flooU3si1v5nfXvNnR+8CXVCnNyiMg3zE2fd+sOYTv84EPUmVgjFzTc5gTjxEIlXd6AHVEZyN4C3SBRvjmdrfbrUpXnz0JAzqC42Iy5VwbABXtcApTsBfK+KzZVJzYtAr6wY4/wL6B3eNPrv0/1Q7V88C2fD3yNP5ladTjY27WNHxRBe6rF9S9BkPpXjvuDEVsmJOswFs3zHzacmuHshyN2+C7O+myhrC4cvz7Fnkx5rMSu9g26WKpSWufZeeBwpxNv1FZQzYqoWHfb6a7DSjokA2dJK1u5DBLyh+HpNd+4I0sKMCEU7njRnXBXW5iWluAFhWaPhAvlZHGiG6TlXoTwqdkTQq96aa2tXkAdvbtV99qJO1gAB23H1KZGSPyHFE2xAkZgReBSEbn0Rtsi8wNQcR7aT32UXJR89CXSkn55zkGBLsjkKDDC0ryBX204a7qkpDZT4tsB93g6AyLuvoWeGTgUOfaXLNfdeocMbqX4+gfPu4Hp0glX5jRZ8BMyaeZNn2Z6Vz55yM='
before_install:
  - openssl aes-256-cbc -K $encrypted_715984db58f8_key -iv $encrypted_715984db58f8_iv -in novatech_deploy.enc -out ~/.ssh/novatech_deploy -d
  - chmod 600 ~/.ssh/novatech_deploy
  - echo "Host github.com" >> ~/.ssh/config
  - echo "  IdentityFile ~/.ssh/novatech_deploy" >> ~/.ssh/config
  - echo "  LogLevel ERROR" >> ~/.ssh/config
  - git clone git@github.com:xtealer/novatech-deployments.git
  - cd novatech-deployments
install:
  - echo "----" >> DEPLOYS.md
  - echo "**CUARENTENA PANAMA WEB**" >> DEPLOY.md
  - echo "TRAVIS BUILD ID - $TRAVIS_JOB_ID" >> DEPLOY.md
  - echo "COMMIT HASH - $TRAVIS_COMMIT" >> DEPLOY.md
  - echo "COMMIT MESSAGE - $TRAVIS_COMMIT_MESSAGE" >> DEPLOY.md
  - echo "----" >> DEPLOY.md
after_install:
  - git add .
  - git commit -a -m "Committed by Travis-CI, build number $TRAVIS_JOB_ID"
  - git push origin master
